[package]
name = "bullet-legacy"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting"]

[dependencies]
bulletformat = "1.7.0"

[profile.release]
panic = 'abort'
strip = true
codegen-units = 1
lto = true
