[workspace]
resolver = "2"
members = [
    "bullet-backends/cpu",
    "bullet-backends/cuda",
    "bullet-core",
    "bullet-tensor",
    "bullet-utils",
]

[workspace.package]
license = "MIT"
authors = ["Jamie Whiting"]

[package]
name = "bullet"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true

[workspace.dependencies]
bulletformat = "0.1.0"

[features]
cuda = ["bullet-tensor/cuda"]

[dependencies]
bulletformat = { workspace = true }
bullet-core = { path = "bullet-core" }
bullet-tensor = { path = "bullet-tensor" }

[profile.release]
panic = 'abort'
strip = true
codegen-units = 1
lto = true
