[workspace]
resolver = "2"
members = ["bullet-utils"]

[workspace.package]
license = "MIT"
authors = ["Jamie Whiting"]

[package]
name = "bullet"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true

[workspace.dependencies]
bulletformat = "0.3.0"

[features]
cuda = []

[dependencies]
bulletformat = { workspace = true }

[build-dependencies]
bindgen = "0.68.1"
cc = "1.0.83"

[profile.release]
panic = 'abort'
strip = true
codegen-units = 1
lto = true
