[package]
name = "bullet_lib"
version = "1.0.0"
edition = "2021"
description = "Neural Network Trainer for 2-Player Games."
authors = ["Jamie Whiting"]
license = "MIT"
repository = "https://github.com/jw1912/bullet"
readme = "README.md"

[dependencies]
bulletformat = { workspace = true }
diffable = { git = "https://github.com/jw1912/diffable.git", tag = "v0.4.0" }
rand = "0.8.5"
rand_distr = "0.4.3"

[build-dependencies]
bindgen = { version = "0.68.1" }
cc = { version = "1.0.83" }

[workspace]
resolver = "2"
members = ["bullet-utils"]

[workspace.package]
license = "MIT"
authors = ["Jamie Whiting"]

[workspace.dependencies]
bulletformat = "1.7.0"

[profile.release]
panic = 'abort'
strip = true
codegen-units = 1
lto = true
