[package]
name = "bullet"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting"]

[profile.release]
panic = 'abort'
strip = true
codegen-units = 1
lto = true

[dependencies]
bindgen = "0.68.1"

[build-dependencies]
bindgen = "0.68.1"
