[package]
name = "bullet-utils"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true

[dependencies]
bulletformat = { workspace = true }
bullet-core = { path = "../bullet-core" }
structopt = "0.3.26"
