[package]
name = "bullet-cpu"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true

[dependencies]
bullet-blas = { path = "../blas", optional = true }
bullet-core = { path = "../../bullet-core" }

[features]
blas = ["bullet-blas"]
