[package]
name = "bullet-cuda"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true

[build-dependencies]
bindgen = "0.68.1"
cc = "1.0.83"

[dependencies]
bullet-core = { path = "../bullet-core" }
