[package]
name = "trainer"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting"]

[dependencies]
common = { path = "../common" }
cpu = { path = "../cpu" }
cuda = { path = "../cuda", optional = true }

[features]
gpu = ["dep:cuda"]