[package]
name = "bullet-tensor"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true

[dependencies]
bullet-core = { path = "../bullet-core" }
bullet-cuda = { path = "../bullet-cuda" }
