[package]
name = "cuda"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting"]

[dependencies]
common = { path = "../common" }
cpu = { path = "../cpu" }

[build-dependencies]
bindgen = "0.68.1"
cc = "1.0.83"
common = { path = "../common" }