on:
    pull_request:
    push:
      branches:
        - main

name: Basic Checks
jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - run: cargo check --all --features gh-actions

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
            component: clippy
        - run: cargo clippy --all --features gh-actions -- -D warnings

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
            component: rustfmt
        - run: cargo fmt --all -- --check